### ISSUE TITLE
Recursive ownership

### ISSUE THREAD

**Issue by lavalamp** [kubernetes-sigs/structured-merge-diff#100]
Another approach towards making the serialized size smaller: if at a given level, the manager owns everything below, store something indicating this rather than enumerating every leaf field. We currently store a `.` to indicate "owns this"; we could store a `!` to indicate "owns this recursively".

Pros:
* If large sections of objects have a single owner, this could make the size much much smaller

Cons:
* On apply, when someone takes ownership of a leaf field, it might drastically change another manager's managed fields. But if we do the compression on encode & decode, it might not need to complicate the code very much.

**Comment by apelisse** [comment]
I'm a little concerned about that. What about defaults? Or values set by mutating webhooks (that we don't track yet). Will you end-up owning these if they are in your "recursive ownership"?

**Comment by lavalamp** [comment]
This is 100% about compressing the existing data. It would not change
behavior at all.
