### ISSUE TITLE
Apply (patch) --server-side failed if service.spec.port does not contain protocol field

### ISSUE THREAD

**Issue by gazarenkov** [kubernetes-sigs/structured-merge-diff#183]
kubectl apply --server-side of this yaml:

>  apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  type: ClusterIP
  selector:
    app: test
  ports:
    - name: http
      port: 80
      targetPort: 8080
      
Failed with 
`Error from server: failed to create typed patch object: .spec.ports: element 0: associative list with keys has an element that omits key field "protocol" (and doesn't have default value)`

Expected to default it with "TCP" (like client side patch/apply does)

> $ kubectl version
> Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T07:38:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by cbandy** [comment]
Fixed in 1.21 perhaps: https://github.com/kubernetes/kubernetes/pull/98576
