### ISSUE TITLE
Modify the behavior of ExtractItems to return only exact paths

### ISSUE THREAD

**Issue by kevindelgado** [kubernetes-sigs/structured-merge-diff#186]
Currently when extracting a path such we extract everything recursively below a given path.

For example:
I apply with `“metadata”:{}`
Someone else adds `“metadata”: { “annotations”: {“foo”:”bar”}}`
When I extract with Fieldset `.metadata` we are going to return `metadata:{“annotations”:{“foo”:”bar”}}` but we want to instead return `metadata:{}`

So what this means for `ExtractItems` is that every path should be treated as a leaf and should empty out the contents of the final path element regardless of what is there.

Another example,
 if we have `”metadata”: {“annotations”: {“foo”: “bar”, “caz”: “dak”}}`
The only way to receive all the annotations should be to Extract a fieldset with both `.metadata.annotations.foo` and `.metadata.annotations.caz` because if you tried to extract `.metadata.annotations` we want this to return `”metadata”:{“annotations”:{}}}`

Atomic fields are an exception to this whereby extracting a path to an atomic field should return everything in that field.

**Comment by apelisse** [comment]
Yeah I think you captured the problem pretty well here.

We could start by adding a few tests to our existing suite with at least:
1. Atomic structures
2. Empty structs
These two are the biggest corner-cases.
