### ISSUE TITLE
Add go mod verify script and pre-submit

### ISSUE THREAD

**Issue by jpbetz** [kubernetes-sigs/structured-merge-diff#271]
go.mod should not be allowed to fall out of sync with vendor/modules.txt.

A hack/verify-vendor.sh style script should be added and then a verify presubmit should be added that calls this verify script.

**Comment by jpbetz** [comment]
Alternatively, could we drop vendor from this repo?

cc @Jefftree

**Comment by Jefftree** [comment]
Created a PR to remove vendor. https://github.com/kubernetes-sigs/structured-merge-diff/pull/272

It seems more convenient than having to remember to vendor every time + adding additional CI scripts.

**Comment by yongruilin** [comment]
Can we close this issue? Vendor has been removed by https://github.com/kubernetes-sigs/structured-merge-diff/pull/272

**Comment by Jefftree** [comment]
> Can we close this issue? Vendor has been removed by #272

Sounds good.

/close
