### ISSUE TITLE
Turn on CI

### ISSUE THREAD

**Issue by lavalamp** [kubernetes-sigs/structured-merge-diff#7]
We should block merges for anything where `go test ...` doesn't pass.

**Comment by mvladev** [comment]
I've tried to enable the CI, but unfortunately the code can't compile (missing external dependency)

```
I1004 20:15:29.264] Call:  /workspace/test-infra/jenkins/../scenarios/execute.py go test ./...
W1004 20:15:29.280] Run: ('go', 'test', './...')
W1004 20:15:29.338] value/unstructured.go:22:2: cannot find package "gopkg.in/yaml.v2" in any of:
W1004 20:15:29.339] 	/usr/local/go/src/gopkg.in/yaml.v2 (from $GOROOT)
W1004 20:15:29.339] 	/go/src/gopkg.in/yaml.v2 (from $GOPATH)
```

The `test-infra` build image is using go `v1.11.1`, so `go.mod` can be used.

**Comment by lavalamp** [comment]
Thanks for the report, we'll definitely set up go.mod for this.

(now just to go figure out how that works...)

**Comment by mvladev** [comment]
@lavalamp I've added that in #16

**Comment by mvladev** [comment]
Hmm what should `test-ifra` call when it clones this repo runs the presubmit (PR) jobs?

Most of the other projects have some small bash script/Makefile:

- https://github.com/kubernetes/test-infra/blob/f00550bff994d708f4a9becb9d1fc78eec0dd9ef/config/jobs/kubernetes/cluster-registry/cluster-registry-config.yaml#L19 
- https://github.com/kubernetes/test-infra/blob/106203e89955131005390b269662fbce58dd63f2/config/jobs/GoogleCloudPlatform/k8s-multicluster-ingress/k8s-multicluster-ingress-config.yaml#L18-L26

**Comment by lavalamp** [comment]
I really want to have zero bash in this repo. go test ./...?

**Comment by mvladev** [comment]
This repo is available at https://k8s-testgrid.appspot.com/
More specifically - https://k8s-testgrid.appspot.com/sig-api-machinery-structured-merge-diff

Reopen this PR if needed.

**Comment by lavalamp** [comment]
@mvladev, thanks a ton!!
