### ISSUE TITLE
Tagging alongside kubernetes

### ISSUE THREAD

**Issue by ecordell** [kubernetes-sigs/structured-merge-diff#76]
It looks like `structured-merge-diff` is a dependency of `k8s.io/apiserver`, but there are no corresponding tags for kubernetes versions like there are in other k8s components. 

For example, when using `kubernetes-1.14.0` tag of `k8s.io/apiserver`, I have to manually pin structured-merge-diff to `e85c7b244fd2` when using go modules.

If anyone comes here with the same issue:
```
go get -m sigs.k8s.io/structured-merge-diff@e85c7b244fd2
```

Is there any chance we can start tagging this repo as well?

**Comment by answer1991** [comment]
We meet same issue, as we use apiserver as v1.14.3 and use this repo as master branch, then compile failed.

**Comment by rohantmp** [comment]
/remove-lifecycle rotten

Same issue
