### ISSUE TITLE
v2 serialization format ideas

### ISSUE THREAD

**Issue by lavalamp** [kubernetes-sigs/structured-merge-diff#99]
We've determined that most of the performance impact is due to the large size change. So, we need to fix that. This issue will tackle improving the format, which is the most obvious avenue for fixing this problem.

Goals:
* concise
* human-readable-ish (just have to beat gzip'd json or proto)

Ideas:
1. Switch to a list format rather than the current map format. Instead of `{"<keytype><key>" : { <children> }}`, we do `[ keytype, <key>, [ <children> ]]`. This flattens every string such that we don't double-encode any strings in keys. keytypes can be numeric if we wish, which shortens them (no need for `"`s. This would be a slight improvement in size since we wouldn't need as many escape characters in strings.
2. Make a "string table". Every time we go to encode a string, look it up from a string table, adding it if it isn't there.
3. The obvious thing to do is number the strings, but we can do better from a readability point of view: use just enough characters to make it unique. We store the short encoding in the string table so that it'll be future proof (adding more strings won't make existing short names ambiguous).
4. We now have to store the string table somewhere. We get the most benefit if we store it once per object rather than once per manager (we still have benefit there from list item keys being repetitive). The format of the string table can just be a json map, and we don't have to duplicate the short name in the long name: `{"me": "tadata", "sp": "ec", "st": "atus", ...}`

Finally, we can provide a default table, so that the shortcuts for common field names don't depend on the order in which they get added to the string table. In terms of storage space it'd be best to just version this default and only encode the differences, but for readability it'd be best to include it in the object. It might make a big difference.

I think this should get us fairly close to what gzip does. gzip has the advantage that it can lose 1 bit per ascii character. But in JSON we'll give that back by base64 encoding it. And what I've described should be much faster than compression/decompression.

Of course we can do even better if we made a truly binary format (imagine combining the `[<keytype>, ` into a single byte), but that won't be more readable than gzip.

**Comment by DirectXMan12** [comment]
> Of course we can do even better if we made a truly binary format (imagine combining the [<keytype>, into a single byte), but that won't be more readable than gzip.

I think that's what alternate representations would bring to the table.  I'd imagine that it'll be relatively rare that any given client wants to read or modify the managers field client side.

Assuming that holds, IMO, it would be fairly beneficial to allow alternate serialization formats -- one fully optimized for performance (size, at the moment) that doesn't take readability into consideration, and one optimized for human readability that doesn't take performance into consideration.  Mixing the two seems like it's going to yield suboptimal results on both ends.

I'd imagine we'd end up with something like

```yaml
metadata:
   managedFields:
      type: json/v1
      fields: "[...]"
```

This could be negotiated via an `Accept` header parameter (a query string parameter would also technically work, but this seems like a pretty good use case for accept headers, given that we're negotiating a content type) -- `Accept: application/json; managedfields="opaque/v1"`,  `Accept: application/json; managedfields="expanded/v1"`, `Accept: application/json; managedfields=none` (don't send managed fields at all), etc.

This would correspondingly set the response content type, and populate the `type` and `fields` field in the result.

This leaves the questio of a single `fields` field vs one `fields` fields per type (`jsonFields`, `binaryFields`, etc).  The benefit of multiple fields is that you could easily match `expanded` to the particular content type in question (json, yaml, proto).  The downside is that adding new forms becomes a lot of work API wise.  With a single semi-opaque `fields []byte` or `fields string` field, you get adding new formats just means implementing the serving logic.  For that reason, I'd lean towards a single-field variant.  This looks a bit similar to how we handle RawExtension in the API (arbitrary object preserved as raw data then decoded in a second step), so it's not w/o precedent.

**Comment by apelisse** [comment]
> With a single semi-opaque fields []byte or fields string field

Just talking about that specific point. I suspect a string would be better than []byte, because it gives us the option to either print a human-readable format,  and if we want to optimize for size/speed,  we can still base64 ourselves.

**Comment by DirectXMan12** [comment]
agreed on that

**Comment by lavalamp** [comment]
"string" is not better in json if the contents of the string will be json-ish, due to quotations... :(

**Comment by DirectXMan12** [comment]
It's not terrible to read in YAML, depending on how the YAML serializer chooses things (block strings alleviate the need for quote escaping), and it's not terrible even when quote-escaped.

There are potentially more ways around this (e.g. make the field arbitrary JSON, and then serialize bytes as base64 string per the usual, and human-readable as a full JSON tree, and then tilt our heads quizzically when asked for human readable but in proto form), but I feel like if `jq .metadata.managedFields.fields | jq .` is sufficient to get "human"-readable output, we're in an ok place.

**Comment by lavalamp** [comment]
The existing format has quote-escapes in it already, so it's pretty terrible...

I've more or less implemented the format I talked about in the OP: https://github.com/kubernetes-sigs/structured-merge-diff/pull/102/files#diff-90f022e64c99ae5344a4c8db1c8cf630R84

No string table yet, I won't go that far without getting everyone on board.
